
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
builder = "nixpacks"
buildCommand = "npm run build"
startCommand = "npm run start:prod"
installCommand = "npm install"

[build.environment]
NPM_CONFIG_USER_AGENT = "npm"
DISABLE_COREPACK = "1"
USE_NPM = "true"
NODE_ENV = "production"